apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-manifest.fullname" . }}-preview
  labels:
    app: {{ .Values.selector.rollout }}-preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.selector.rollout }}-preview

