apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "rollout-manifest.fullname" . }}
  labels:
    app: {{ .Values.selector.deployment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selector.deployment }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.deployment }}
    spec:
      containers:
      - name: flask-socket
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 30
  strategy:
    blueGreen:
      activeService: {{ include "rollout-manifest.fullname" . }}
      previewService: {{ include "rollout-manifest.fullname" . }}-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30

